import 'dart:io';

String getLocaleCurrency() {
  try {
    final locale = Platform.localeName;
    final countryCode = locale.split('_').last.split('.').first.toUpperCase();
    return _countryToCurrency[countryCode] ?? 'USD';
  } catch (_) {
    return 'USD';
  }
}

String getCurrencySymbol(String currencyCode) {
  final normalizedCode = currencyCode.trim().toUpperCase();

  return currencySymbols[normalizedCode] ?? normalizedCode;
}

const Map<String, String> currencySymbols = {
  'AED': 'د.إ',
  'AFN': '؋',
  'ALL': 'L',
  'AMD': '֏',
  'AOA': 'Kz',
  'ARS': r'$',
  'AUD': r'$',
  'BDT': '৳',
  'BGN': 'лв',
  'BHD': 'د.ب',
  'BRL': r'R$',
  'CAD': r'$',
  'CHF': 'CHF',
  'CNY': '¥',
  'CZK': 'Kč',
  'DKK': 'kr',
  'EGP': 'E£',
  'EUR': '€',
  'GBP': '£',
  'GHS': '₵',
  'HKD': r'$',
  'HUF': 'Ft',
  'IDR': 'Rp',
  'ILS': '₪',
  'INR': '₹',
  'JPY': '¥',
  'KRW': '₩',
  'KWD': 'د.ك',
  'LKR': 'Rs',
  'MXN': r'$',
  'MYR': 'RM',
  'NGN': '₦',
  'NOK': 'kr',
  'NPR': 'रू',
  'NZD': r'$',
  'PHP': '₱',
  'PKR': 'Rs',
  'PLN': 'zł',
  'QAR': 'ر.ق',
  'RON': 'lei',
  'RUB': '₽',
  'SAR': 'ر.س',
  'SEK': 'kr',
  'SGD': r'$',
  'THB': '฿',
  'TRY': '₺',
  'TWD': r'NT$',
  'UAH': '₴',
  'USD': r'$',
  'VND': '₫',
  'ZAR': 'R',
};

const _countryToCurrency = {
  'AE': 'AED',
  'AF': 'AFN',
  'AL': 'ALL',
  'AM': 'AMD',
  'AO': 'AOA',
  'AR': 'ARS',
  'AU': 'AUD',
  'AW': 'AWG',
  'AZ': 'AZN',
  'BA': 'BAM',
  'BB': 'BBD',
  'BD': 'BDT',
  'BG': 'BGN',
  'BH': 'BHD',
  'BI': 'BIF',
  'BM': 'BMD',
  'BN': 'BND',
  'BO': 'BOB',
  'BR': 'BRL',
  'BS': 'BSD',
  'BT': 'BTN',
  'BW': 'BWP',
  'BY': 'BYN',
  'BZ': 'BZD',
  'CA': 'CAD',
  'CD': 'CDF',
  'CH': 'CHF',
  'CL': 'CLP',
  'CN': 'CNY',
  'CO': 'COP',
  'CR': 'CRC',
  'CU': 'CUP',
  'CV': 'CVE',
  'CZ': 'CZK',
  'DJ': 'DJF',
  'DK': 'DKK',
  'DO': 'DOP',
  'DZ': 'DZD',
  'EG': 'EGP',
  'ER': 'ERN',
  'ET': 'ETB',
  'FJ': 'FJD',
  'FK': 'FKP',
  'GB': 'GBP',
  'GE': 'GEL',
  'GH': 'GHS',
  'GI': 'GIP',
  'GM': 'GMD',
  'GN': 'GNF',
  'GT': 'GTQ',
  'GY': 'GYD',
  'HK': 'HKD',
  'HN': 'HNL',
  'HR': 'HRK',
  'HT': 'HTG',
  'HU': 'HUF',
  'ID': 'IDR',
  'IL': 'ILS',
  'IN': 'INR',
  'IQ': 'IQD',
  'IR': 'IRR',
  'IS': 'ISK',
  'JM': 'JMD',
  'JO': 'JOD',
  'JP': 'JPY',
  'KE': 'KES',
  'KG': 'KGS',
  'KH': 'KHR',
  'KM': 'KMF',
  'KP': 'KPW',
  'KR': 'KRW',
  'KW': 'KWD',
  'KY': 'KYD',
  'KZ': 'KZT',
  'LA': 'LAK',
  'LB': 'LBP',
  'LK': 'LKR',
  'LR': 'LRD',
  'LS': 'LSL',
  'LY': 'LYD',
  'MA': 'MAD',
  'MD': 'MDL',
  'MG': 'MGA',
  'MK': 'MKD',
  'MM': 'MMK',
  'MN': 'MNT',
  'MO': 'MOP',
  'MR': 'MRU',
  'MU': 'MUR',
  'MV': 'MVR',
  'MW': 'MWK',
  'MX': 'MXN',
  'MY': 'MYR',
  'MZ': 'MZN',
  'NA': 'NAD',
  'NG': 'NGN',
  'NI': 'NIO',
  'NO': 'NOK',
  'NP': 'NPR',
  'NZ': 'NZD',
  'OM': 'OMR',
  'PA': 'PAB',
  'PE': 'PEN',
  'PG': 'PGK',
  'PH': 'PHP',
  'PK': 'PKR',
  'PL': 'PLN',
  'PY': 'PYG',
  'QA': 'QAR',
  'RO': 'RON',
  'RS': 'RSD',
  'RU': 'RUB',
  'RW': 'RWF',
  'SA': 'SAR',
  'SB': 'SBD',
  'SC': 'SCR',
  'SD': 'SDG',
  'SE': 'SEK',
  'SG': 'SGD',
  'SH': 'SHP',
  'SL': 'SLL',
  'SO': 'SOS',
  'SR': 'SRD',
  'ST': 'STN',
  'SV': 'SVC',
  'SY': 'SYP',
  'SZ': 'SZL',
  'TH': 'THB',
  'TJ': 'TJS',
  'TM': 'TMT',
  'TN': 'TND',
  'TO': 'TOP',
  'TR': 'TRY',
  'TT': 'TTD',
  'TW': 'TWD',
  'TZ': 'TZS',
  'UA': 'UAH',
  'UG': 'UGX',
  'US': 'USD',
  'UY': 'UYU',
  'UZ': 'UZS',
  'VE': 'VES',
  'VN': 'VND',
  'VU': 'VUV',
  'WS': 'WST',
  'YE': 'YER',
  'ZA': 'ZAR',
  'ZM': 'ZMW',
  'ZW': 'ZWL',
};
const Map<String, Map<String, String>> currencyDetails = {
  'AED': {
    'flag': '🇦🇪',
    'name': 'UAE Dirham',
    'country': 'United Arab Emirates',
  },
  'AFN': {'flag': '🇦🇫', 'name': 'Afghan Afghani', 'country': 'Afghanistan'},
  'ALL': {'flag': '🇦🇱', 'name': 'Albanian Lek', 'country': 'Albania'},
  'AMD': {'flag': '🇦🇲', 'name': 'Armenian Dram', 'country': 'Armenia'},
  'ANG': {
    'flag': '🇳🇱',
    'name': 'Netherlands Antillean Guilder',
    'country': 'Netherlands Antilles',
  },
  'AOA': {'flag': '🇦🇴', 'name': 'Angolan Kwanza', 'country': 'Angola'},
  'ARS': {'flag': '🇦🇷', 'name': 'Argentine Peso', 'country': 'Argentina'},
  'AUD': {'flag': '🇦🇺', 'name': 'Australian Dollar', 'country': 'Australia'},
  'AWG': {'flag': '🇦🇼', 'name': 'Aruban Florin', 'country': 'Aruba'},
  'AZN': {'flag': '🇦🇿', 'name': 'Azerbaijani Manat', 'country': 'Azerbaijan'},
  'BAM': {
    'flag': '🇧🇦',
    'name': 'Convertible Mark',
    'country': 'Bosnia & Herzegovina',
  },
  'BBD': {'flag': '🇧🇧', 'name': 'Barbadian Dollar', 'country': 'Barbados'},
  'BDT': {'flag': '🇧🇩', 'name': 'Bangladeshi Taka', 'country': 'Bangladesh'},
  'BGN': {'flag': '🇧🇬', 'name': 'Bulgarian Lev', 'country': 'Bulgaria'},
  'BHD': {'flag': '🇧🇭', 'name': 'Bahraini Dinar', 'country': 'Bahrain'},
  'BIF': {'flag': '🇧🇮', 'name': 'Burundian Franc', 'country': 'Burundi'},
  'BMD': {'flag': '🇧🇲', 'name': 'Bermudan Dollar', 'country': 'Bermuda'},
  'BND': {'flag': '🇧🇳', 'name': 'Brunei Dollar', 'country': 'Brunei'},
  'BOB': {'flag': '🇧🇴', 'name': 'Bolivian Boliviano', 'country': 'Bolivia'},
  'BRL': {'flag': '🇧🇷', 'name': 'Brazilian Real', 'country': 'Brazil'},
  'BSD': {'flag': '🇧🇸', 'name': 'Bahamian Dollar', 'country': 'Bahamas'},
  'BTN': {'flag': '🇧🇹', 'name': 'Bhutanese Ngultrum', 'country': 'Bhutan'},
  'BWP': {'flag': '🇧🇼', 'name': 'Botswanan Pula', 'country': 'Botswana'},
  'BYN': {'flag': '🇧🇾', 'name': 'Belarusian Ruble', 'country': 'Belarus'},
  'BZD': {'flag': '🇧🇿', 'name': 'Belize Dollar', 'country': 'Belize'},
  'CAD': {'flag': '🇨🇦', 'name': 'Canadian Dollar', 'country': 'Canada'},
  'CDF': {'flag': '🇨🇩', 'name': 'Congolese Franc', 'country': 'DR Congo'},
  'CHF': {'flag': '🇨🇭', 'name': 'Swiss Franc', 'country': 'Switzerland'},
  'CLP': {'flag': '🇨🇱', 'name': 'Chilean Peso', 'country': 'Chile'},
  'CNY': {'flag': '🇨🇳', 'name': 'Chinese Yuan', 'country': 'China'},
  'COP': {'flag': '🇨🇴', 'name': 'Colombian Peso', 'country': 'Colombia'},
  'CRC': {'flag': '🇨🇷', 'name': 'Costa Rican Colón', 'country': 'Costa Rica'},
  'CUP': {'flag': '🇨🇺', 'name': 'Cuban Peso', 'country': 'Cuba'},
  'CVE': {
    'flag': '🇨🇻',
    'name': 'Cape Verdean Escudo',
    'country': 'Cape Verde',
  },
  'CZK': {'flag': '🇨🇿', 'name': 'Czech Koruna', 'country': 'Czech Republic'},
  'DJF': {'flag': '🇩🇯', 'name': 'Djiboutian Franc', 'country': 'Djibouti'},
  'DKK': {'flag': '🇩🇰', 'name': 'Danish Krone', 'country': 'Denmark'},
  'DOP': {
    'flag': '🇩🇴',
    'name': 'Dominican Peso',
    'country': 'Dominican Republic',
  },
  'DZD': {'flag': '🇩🇿', 'name': 'Algerian Dinar', 'country': 'Algeria'},
  'EGP': {'flag': '🇪🇬', 'name': 'Egyptian Pound', 'country': 'Egypt'},
  'ERN': {'flag': '🇪🇷', 'name': 'Eritrean Nakfa', 'country': 'Eritrea'},
  'ETB': {'flag': '🇪🇹', 'name': 'Ethiopian Birr', 'country': 'Ethiopia'},
  'EUR': {'flag': '🇪🇺', 'name': 'Euro', 'country': 'European Union'},
  'FJD': {'flag': '🇫🇯', 'name': 'Fijian Dollar', 'country': 'Fiji'},
  'FKP': {
    'flag': '🇫🇰',
    'name': 'Falkland Islands Pound',
    'country': 'Falkland Islands',
  },
  'GBP': {'flag': '🇬🇧', 'name': 'British Pound', 'country': 'United Kingdom'},
  'GEL': {'flag': '🇬🇪', 'name': 'Georgian Lari', 'country': 'Georgia'},
  'GHS': {'flag': '🇬🇭', 'name': 'Ghanaian Cedi', 'country': 'Ghana'},
  'GIP': {'flag': '🇬🇮', 'name': 'Gibraltar Pound', 'country': 'Gibraltar'},
  'GMD': {'flag': '🇬🇲', 'name': 'Gambian Dalasi', 'country': 'Gambia'},
  'GNF': {'flag': '🇬🇳', 'name': 'Guinean Franc', 'country': 'Guinea'},
  'GTQ': {'flag': '🇬🇹', 'name': 'Guatemalan Quetzal', 'country': 'Guatemala'},
  'GYD': {'flag': '🇬🇾', 'name': 'Guyanaese Dollar', 'country': 'Guyana'},
  'HKD': {'flag': '🇭🇰', 'name': 'Hong Kong Dollar', 'country': 'Hong Kong'},
  'HNL': {'flag': '🇭🇳', 'name': 'Honduran Lempira', 'country': 'Honduras'},
  'HRK': {'flag': '🇭🇷', 'name': 'Croatian Kuna', 'country': 'Croatia'},
  'HTG': {'flag': '🇭🇹', 'name': 'Haitian Gourde', 'country': 'Haiti'},
  'HUF': {'flag': '🇭🇺', 'name': 'Hungarian Forint', 'country': 'Hungary'},
  'IDR': {'flag': '🇮🇩', 'name': 'Indonesian Rupiah', 'country': 'Indonesia'},
  'ILS': {'flag': '🇮🇱', 'name': 'Israeli New Shekel', 'country': 'Israel'},
  'INR': {'flag': '🇮🇳', 'name': 'Indian Rupee', 'country': 'India'},
  'IQD': {'flag': '🇮🇶', 'name': 'Iraqi Dinar', 'country': 'Iraq'},
  'IRR': {'flag': '🇮🇷', 'name': 'Iranian Rial', 'country': 'Iran'},
  'ISK': {'flag': '🇮🇸', 'name': 'Icelandic Króna', 'country': 'Iceland'},
  'JMD': {'flag': '🇯🇲', 'name': 'Jamaican Dollar', 'country': 'Jamaica'},
  'JOD': {'flag': '🇯🇴', 'name': 'Jordanian Dinar', 'country': 'Jordan'},
  'JPY': {'flag': '🇯🇵', 'name': 'Japanese Yen', 'country': 'Japan'},
  'KES': {'flag': '🇰🇪', 'name': 'Kenyan Shilling', 'country': 'Kenya'},
  'KGS': {'flag': '🇰🇬', 'name': 'Kyrgystani Som', 'country': 'Kyrgyzstan'},
  'KHR': {'flag': '🇰🇭', 'name': 'Cambodian Riel', 'country': 'Cambodia'},
  'KMF': {'flag': '🇰🇲', 'name': 'Comorian Franc', 'country': 'Comoros'},
  'KPW': {'flag': '🇰🇵', 'name': 'North Korean Won', 'country': 'North Korea'},
  'KRW': {'flag': '🇰🇷', 'name': 'South Korean Won', 'country': 'South Korea'},
  'KWD': {'flag': '🇰🇼', 'name': 'Kuwaiti Dinar', 'country': 'Kuwait'},
  'KYD': {
    'flag': '🇰🇾',
    'name': 'Cayman Islands Dollar',
    'country': 'Cayman Islands',
  },
  'KZT': {'flag': '🇰🇿', 'name': 'Kazakhstani Tenge', 'country': 'Kazakhstan'},
  'LAK': {'flag': '🇱🇦', 'name': 'Laotian Kip', 'country': 'Laos'},
  'LBP': {'flag': '🇱🇧', 'name': 'Lebanese Pound', 'country': 'Lebanon'},
  'LKR': {'flag': '🇱🇰', 'name': 'Sri Lankan Rupee', 'country': 'Sri Lanka'},
  'LRD': {'flag': '🇱🇷', 'name': 'Liberian Dollar', 'country': 'Liberia'},
  'LSL': {'flag': '🇱🇸', 'name': 'Lesotho Loti', 'country': 'Lesotho'},
  'LYD': {'flag': '🇱🇾', 'name': 'Libyan Dinar', 'country': 'Libya'},
  'MAD': {'flag': '🇲🇦', 'name': 'Moroccan Dirham', 'country': 'Morocco'},
  'MDL': {'flag': '🇲🇩', 'name': 'Moldovan Leu', 'country': 'Moldova'},
  'MGA': {'flag': '🇲🇬', 'name': 'Malagasy Ariary', 'country': 'Madagascar'},
  'MKD': {
    'flag': '🇲🇰',
    'name': 'Macedonian Denar',
    'country': 'North Macedonia',
  },
  'MMK': {'flag': '🇲🇲', 'name': 'Myanmar Kyat', 'country': 'Myanmar'},
  'MNT': {'flag': '🇲🇳', 'name': 'Mongolian Tögrög', 'country': 'Mongolia'},
  'MOP': {'flag': '🇲🇴', 'name': 'Macanese Pataca', 'country': 'Macau'},
  'MRU': {
    'flag': '🇲🇷',
    'name': 'Mauritanian Ouguiya',
    'country': 'Mauritania',
  },
  'MUR': {'flag': '🇲🇺', 'name': 'Mauritian Rupee', 'country': 'Mauritius'},
  'MVR': {'flag': '🇲🇻', 'name': 'Maldivian Rufiyaa', 'country': 'Maldives'},
  'MWK': {'flag': '🇲🇼', 'name': 'Malawian Kwacha', 'country': 'Malawi'},
  'MXN': {'flag': '🇲🇽', 'name': 'Mexican Peso', 'country': 'Mexico'},
  'MYR': {'flag': '🇲🇾', 'name': 'Malaysian Ringgit', 'country': 'Malaysia'},
  'MZN': {
    'flag': '🇲🇿',
    'name': 'Mozambican Metical',
    'country': 'Mozambique',
  },
  'NAD': {'flag': '🇳🇦', 'name': 'Namibian Dollar', 'country': 'Namibia'},
  'NGN': {'flag': '🇳🇬', 'name': 'Nigerian Naira', 'country': 'Nigeria'},
  'NIO': {'flag': '🇳🇮', 'name': 'Nicaraguan Córdoba', 'country': 'Nicaragua'},
  'NOK': {'flag': '🇳🇴', 'name': 'Norwegian Krone', 'country': 'Norway'},
  'NPR': {'flag': '🇳🇵', 'name': 'Nepalese Rupee', 'country': 'Nepal'},
  'NZD': {
    'flag': '🇳🇿',
    'name': 'New Zealand Dollar',
    'country': 'New Zealand',
  },
  'OMR': {'flag': '🇴🇲', 'name': 'Omani Rial', 'country': 'Oman'},
  'PAB': {'flag': '🇵🇦', 'name': 'Panamanian Balboa', 'country': 'Panama'},
  'PEN': {'flag': '🇵🇪', 'name': 'Peruvian Sol', 'country': 'Peru'},
  'PGK': {
    'flag': '🇵🇬',
    'name': 'Papua New Guinean Kina',
    'country': 'Papua New Guinea',
  },
  'PHP': {'flag': '🇵🇭', 'name': 'Philippine Peso', 'country': 'Philippines'},
  'PKR': {'flag': '🇵🇰', 'name': 'Pakistani Rupee', 'country': 'Pakistan'},
  'PLN': {'flag': '🇵🇱', 'name': 'Polish Złoty', 'country': 'Poland'},
  'PYG': {'flag': '🇵🇾', 'name': 'Paraguayan Guaraní', 'country': 'Paraguay'},
  'QAR': {'flag': '🇶🇦', 'name': 'Qatari Rial', 'country': 'Qatar'},
  'RON': {'flag': '🇷🇴', 'name': 'Romanian Leu', 'country': 'Romania'},
  'RSD': {'flag': '🇷🇸', 'name': 'Serbian Dinar', 'country': 'Serbia'},
  'RUB': {'flag': '🇷🇺', 'name': 'Russian Ruble', 'country': 'Russia'},
  'RWF': {'flag': '🇷🇼', 'name': 'Rwandan Franc', 'country': 'Rwanda'},
  'SAR': {'flag': '🇸🇦', 'name': 'Saudi Riyal', 'country': 'Saudi Arabia'},
  'SBD': {
    'flag': '🇸🇧',
    'name': 'Solomon Islands Dollar',
    'country': 'Solomon Islands',
  },
  'SCR': {'flag': '🇸🇨', 'name': 'Seychellois Rupee', 'country': 'Seychelles'},
  'SDG': {'flag': '🇸🇩', 'name': 'Sudanese Pound', 'country': 'Sudan'},
  'SEK': {'flag': '🇸🇪', 'name': 'Swedish Krona', 'country': 'Sweden'},
  'SGD': {'flag': '🇸🇬', 'name': 'Singapore Dollar', 'country': 'Singapore'},
  'SHP': {
    'flag': '🇸🇭',
    'name': 'Saint Helena Pound',
    'country': 'Saint Helena',
  },
  'SLL': {
    'flag': '🇸🇱',
    'name': 'Sierra Leonean Leone',
    'country': 'Sierra Leone',
  },
  'SOS': {'flag': '🇸🇴', 'name': 'Somali Shilling', 'country': 'Somalia'},
  'SRD': {'flag': '🇸🇷', 'name': 'Surinamese Dollar', 'country': 'Suriname'},
  'STN': {
    'flag': '🇸🇹',
    'name': 'São Tomé & Príncipe Dobra',
    'country': 'São Tomé & Príncipe',
  },
  'SVC': {'flag': '🇸🇻', 'name': 'Salvadoran Colón', 'country': 'El Salvador'},
  'SYP': {'flag': '🇸🇾', 'name': 'Syrian Pound', 'country': 'Syria'},
  'SZL': {'flag': '🇸🇿', 'name': 'Swazi Lilangeni', 'country': 'Eswatini'},
  'THB': {'flag': '🇹🇭', 'name': 'Thai Baht', 'country': 'Thailand'},
  'TJS': {
    'flag': '🇹🇯',
    'name': 'Tajikistani Somoni',
    'country': 'Tajikistan',
  },
  'TMT': {
    'flag': '🇹🇲',
    'name': 'Turkmenistani Manat',
    'country': 'Turkmenistan',
  },
  'TND': {'flag': '🇹🇳', 'name': 'Tunisian Dinar', 'country': 'Tunisia'},
  'TOP': {'flag': '🇹🇴', 'name': 'Tongan Paʻanga', 'country': 'Tonga'},
  'TRY': {'flag': '🇹🇷', 'name': 'Turkish Lira', 'country': 'Turkey'},
  'TTD': {
    'flag': '🇹🇹',
    'name': 'Trinidad & Tobago Dollar',
    'country': 'Trinidad & Tobago',
  },
  'TWD': {'flag': '🇹🇼', 'name': 'Taiwan Dollar', 'country': 'Taiwan'},
  'TZS': {'flag': '🇹🇿', 'name': 'Tanzanian Shilling', 'country': 'Tanzania'},
  'UAH': {'flag': '🇺🇦', 'name': 'Ukrainian Hryvnia', 'country': 'Ukraine'},
  'UGX': {'flag': '🇺🇬', 'name': 'Ugandan Shilling', 'country': 'Uganda'},
  'USD': {'flag': '🇺🇸', 'name': 'US Dollar', 'country': 'United States'},
  'UYU': {'flag': '🇺🇾', 'name': 'Uruguayan Peso', 'country': 'Uruguay'},
  'UZS': {'flag': '🇺🇿', 'name': 'Uzbekistani Som', 'country': 'Uzbekistan'},
  'VES': {'flag': '🇻🇪', 'name': 'Venezuelan Bolívar', 'country': 'Venezuela'},
  'VND': {'flag': '🇻🇳', 'name': 'Vietnamese Dong', 'country': 'Vietnam'},
  'VUV': {'flag': '🇻🇺', 'name': 'Vanuatu Vatu', 'country': 'Vanuatu'},
  'WST': {'flag': '🇼🇸', 'name': 'Samoan Tala', 'country': 'Samoa'},
  'XAF': {
    'flag': '🇨🇲',
    'name': 'Central African CFA Franc',
    'country': 'Central Africa',
  },
  'XCD': {
    'flag': '🇦🇬',
    'name': 'East Caribbean Dollar',
    'country': 'East Caribbean',
  },
  'XOF': {
    'flag': '🇸🇳',
    'name': 'West African CFA Franc',
    'country': 'West Africa',
  },
  'XPF': {'flag': '🇵🇫', 'name': 'CFP Franc', 'country': 'French Polynesia'},
  'YER': {'flag': '🇾🇪', 'name': 'Yemeni Rial', 'country': 'Yemen'},
  'ZAR': {
    'flag': '🇿🇦',
    'name': 'South African Rand',
    'country': 'South Africa',
  },
  'ZMW': {'flag': '🇿🇲', 'name': 'Zambian Kwacha', 'country': 'Zambia'},
  'ZWL': {'flag': '🇿🇼', 'name': 'Zimbabwean Dollar', 'country': 'Zimbabwe'},
};
