// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaAkJO8ABEBfETGj1UgjVLX-AaOs6kFhw',
    appId: '1:25983957579:web:8c59d03513582c1342ebce',
    messagingSenderId: '25983957579',
    projectId: 'subzero-c40f0',
    authDomain: 'subzero-c40f0.firebaseapp.com',
    storageBucket: 'subzero-c40f0.firebasestorage.app',
    measurementId: 'G-XFS8BS88GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoTxXZxFv0U4nHyXS05IyOUsLTMueb3s0',
    appId: '1:25983957579:android:bd280a576cc7238f42ebce',
    messagingSenderId: '25983957579',
    projectId: 'subzero-c40f0',
    storageBucket: 'subzero-c40f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN-Pb12wTOMf51cPvAi-r_vLhwOF5hPQY',
    appId: '1:25983957579:ios:d193f2d58be7534a42ebce',
    messagingSenderId: '25983957579',
    projectId: 'subzero-c40f0',
    storageBucket: 'subzero-c40f0.firebasestorage.app',
    iosBundleId: 'np.com.subzero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN-Pb12wTOMf51cPvAi-r_vLhwOF5hPQY',
    appId: '1:25983957579:ios:d193f2d58be7534a42ebce',
    messagingSenderId: '25983957579',
    projectId: 'subzero-c40f0',
    storageBucket: 'subzero-c40f0.firebasestorage.app',
    iosBundleId: 'np.com.subzero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaAkJO8ABEBfETGj1UgjVLX-AaOs6kFhw',
    appId: '1:25983957579:web:5e954dcaf3d984bf42ebce',
    messagingSenderId: '25983957579',
    projectId: 'subzero-c40f0',
    authDomain: 'subzero-c40f0.firebaseapp.com',
    storageBucket: 'subzero-c40f0.firebasestorage.app',
    measurementId: 'G-1JME8HBNQ8',
  );
}
